# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7aae5939848d3591fa75920b36e95de12af75448c75af2f6e2e19d7cbb270b5fb9440d0b98cc3e9f7f7055a2e34c359b25adfb8b1105c135921b877d8d44b1b0

test:
  secret_key_base: f3e5be6f48355928d575f30d4aed54d53a541192f4d3f3d19ceb10109507e133f5e78abb9e011c294be9c86a824b7c4e43a7935db3ebbe9f203afed7f2c7806e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
